var Activity = {
	
	ZERO: 0,
	INICIAR: 4,
	
	VALIDAR_COMPOSICAO: 5,
	ELABORAR_ANALISES: 15,
	ELABORAR_DOCUMENTAL_ACODE: 20,
	AVALIAR_MINUTA: 36,
	COLHER_ASSINATURAS: 38,
	ATUALIZAR_CONTRATO: 22,
	PROBLEMA_ASSOCIAR_SMS: 50,
	PROBLEMA_ATUALIZAR_SMS: 64,

	SERVICO_ASSOCIAR_SMS: 44,
	SERVICO_ATUALIZAR_SMS: 60,

	GATEWAY_RETORNA_SOLICITANTE: 29,
	GATEWAY_ADITIVO: 34,

	FIM_CONCLUIDA: 26
};