SELECT  DISTINCT DAT_MOVTO as DATA_INICIO , MIN(HRA_MOVTO) as HORA_INICIO, MAX(HRA_MOVTO) as HORA_FIM, COD_MATR_REQUISIT as USUARIO, COUNT(P.NUM_PROCES) as MOVIMENTACOE  FROM proces_workflow AS C  JOIN histor_proces AS P  ON C.NUM_PROCES = P.NUM_PROCES  WHERE COD_DEF_PROCES = 'CALCULODECOMISSÃO1'  AND  NUM_SEQ_ESTADO = 67 GROUP BY DAT_MOVTO,COD_MATR_REQUISIT  ORDER BY 1


-- 386 -----> (24/03/2019)

--SELECT DISTINCT DAT_MOVTO, count(NUM_SEQ_ESTADO) as movimento  FROM proces_workflow AS C JOIN histor_proces AS P ON C.NUM_PROCES = P.NUM_PROCES WHERE C.COD_DEF_PROCES = 'CALCULODECOMISSÃO1' AND NUM_SEQ_ESTADO = 67 GROUP BY DAT_MOVTO ORDER BY 1