
-- SELECT * FROM ANEXO_PROCES WHERE NUM_SEQ_MOVTO_ORIG = 1   

SELECT DISTINCT top 100  H.NUM_PROCES, M.EMPNOME, COUNT(H.NUM_PROCES) AS SOLICITACOES FROM DOCUMENTO AS D 
         JOIN ANEXO_PROCES AS A ON A.NUM_SEQ_MOVTO_ORIG = D.VERSAO_ATIVA
         JOIN ML001855 AS M ON D.NR_DOCUMENTO = M.DOCUMENTID
         JOIN histor_proces AS H ON H.NUM_PROCES = A.NUM_PROCES  
         JOIN PROCES_WORKFLOW as P on H.NUM_PROCES = P.NUM_PROCES
         WHERE  P.[STATUS] = 0 GROUP by M.EMPNOME,h.NUM_PROCES ORDER BY 1
         

     --   SELECT * FROM ANEXO_PROCES
    
    --WHERE VERSAO_ATIVA = 1   

-- SELECT   DISTINCT(C.NUM_PROCES) AS processos  
--     FROM proces_workflow AS C  
--     JOIN histor_proces AS P  
--     ON C.NUM_PROCES = P.NUM_PROCES  
--     WHERE COD_DEF_PROCES = 'CALCULODECOMISSÃO1' 
--     AND  NUM_SEQ_ESTADO = 67 
--     AND [STATUS] = '0' 
--     GROUP BY C.NUM_PROCES ORDER BY 1