var ListaSeguroOdonto = new Array();
ListaSeguroOdonto.push("AGENTE DE PORTARIA");
ListaSeguroOdonto.push("AGENTE DE RECRUTAMENTO"); 
ListaSeguroOdonto.push("AJUDANTE PRATICO DE ELETRICISTA");
ListaSeguroOdonto.push("AJUDANTE PRATICO DE HIDRAULICA");
ListaSeguroOdonto.push("APONTADOR");
ListaSeguroOdonto.push("APRENDIZ");
ListaSeguroOdonto.push("APRENDIZ SENAI");
ListaSeguroOdonto.push("ARMADOR");
ListaSeguroOdonto.push("AUTONOMO A");
ListaSeguroOdonto.push("AUTONOMO B");
ListaSeguroOdonto.push("AUXILIAR DE ALMOXARIFE");
ListaSeguroOdonto.push("AUXILIAR DE ELETRICA");
ListaSeguroOdonto.push("AUXILIAR DE ELETRICISTA");
ListaSeguroOdonto.push("AUXILIAR DE LABORATORIO DE CONCRETO");
ListaSeguroOdonto.push("AUXILIAR DE SEGURANCA DO TRABALHO");
ListaSeguroOdonto.push("AUXILIAR DE TOPOGRAFIA");
ListaSeguroOdonto.push("AZULEJISTA");
ListaSeguroOdonto.push("BETONEIRO");
ListaSeguroOdonto.push("BOMBEIRO");
ListaSeguroOdonto.push("BOMBEIRO HIDRAULICO");
ListaSeguroOdonto.push("CARPINTEIRO");
ListaSeguroOdonto.push("CARPINTEIRO DE ESQUADRIA");
ListaSeguroOdonto.push("ELETRICISTA");
ListaSeguroOdonto.push("ELETRICISTA PL");
ListaSeguroOdonto.push("ENCANADOR");
ListaSeguroOdonto.push("ESTAGIARIO");
ListaSeguroOdonto.push("ESTAGIARIO DE ENGENHARIA");
ListaSeguroOdonto.push("ESTAGIARIO DE TECNICO EM EDIFICACOES");
ListaSeguroOdonto.push("ESTAGIARIO DE TECNICO EM SEGURANCA ");
ListaSeguroOdonto.push("ESTAGIARIO DE TECNOLOGIA DE EDIFICIOS");
ListaSeguroOdonto.push("ESTAGIARIO DO ENSINO SUPERIOR");
ListaSeguroOdonto.push("ESTAGIARIO DO ENSINO TECNICO");
ListaSeguroOdonto.push("FAXINEIRO");
ListaSeguroOdonto.push("FERREIRO ARMADOR");
ListaSeguroOdonto.push("GESSEIRO");
ListaSeguroOdonto.push("GUINCHEIRO");
ListaSeguroOdonto.push("IMPERMEABILIZADOR");
ListaSeguroOdonto.push("INSTRUTOR DE FORMA");
ListaSeguroOdonto.push("LADRILHEIRO");
ListaSeguroOdonto.push("LIDER INSTRUTOR DE FORMA");
ListaSeguroOdonto.push("MARCENEIRO");
ListaSeguroOdonto.push("MARTELETEIRO");
ListaSeguroOdonto.push("MECANICO DE MANUTENCAO");
ListaSeguroOdonto.push("MEIO OFICIAL");
ListaSeguroOdonto.push("MEIO OFICIAL ARMADOR");
ListaSeguroOdonto.push("MEIO OFICIAL CARPINTEIRO");
ListaSeguroOdonto.push("MEIO OFICIAL DE BOMBEIRO");
ListaSeguroOdonto.push("MEIO OFICIAL DE GESSEIRO");
ListaSeguroOdonto.push("MEIO OFICIAL DE MONTADOR");
ListaSeguroOdonto.push("MEIO OFICIAL ELETRICISTA");
ListaSeguroOdonto.push("MEIO OFICIAL ENCANADOR");
ListaSeguroOdonto.push("MEIO OFICIAL PEDREIRO");
ListaSeguroOdonto.push("MEIO OFICIAL PINTOR");
ListaSeguroOdonto.push("MEIO OFICIAL SOLDADOR");
ListaSeguroOdonto.push("MONTADOR");
ListaSeguroOdonto.push("MOTOBOY");
ListaSeguroOdonto.push("MOTORISTA");
ListaSeguroOdonto.push("OPERADOR DE BETONEIRA");
ListaSeguroOdonto.push("OPERADOR DE GRADALL");
ListaSeguroOdonto.push("OPERADOR DE GRUA");
ListaSeguroOdonto.push("OPERADOR DE GUINCHO");
ListaSeguroOdonto.push("OPERADOR DE MANIPULADORES TELESCOPICOS");
ListaSeguroOdonto.push("OPERADOR DE MAQUINA");
ListaSeguroOdonto.push("OPERADOR DE POLICORTE");
ListaSeguroOdonto.push("OPERADOR DE PRANCHA");
ListaSeguroOdonto.push("OPERADOR DE REFRATARIA");
ListaSeguroOdonto.push("PEDREIRO");
ListaSeguroOdonto.push("PEDREIRO DE FACHADA");
ListaSeguroOdonto.push("PINTOR");
ListaSeguroOdonto.push("PORTEIRO");
ListaSeguroOdonto.push("PROFISSIONAL LIDER");
ListaSeguroOdonto.push("REJUNTADOR");
ListaSeguroOdonto.push("SERRALHEIRO");
ListaSeguroOdonto.push("SERVENTE");
ListaSeguroOdonto.push("SERVENTE HABILITADO");
ListaSeguroOdonto.push("SINALIZADOR DE GRUA");
ListaSeguroOdonto.push("SOLDADOR");
ListaSeguroOdonto.push("TECNICO DE ESTRADAS");
ListaSeguroOdonto.push("TECNICO DE MANUTENCAO");
ListaSeguroOdonto.push("TECNICO EM INSTALACOES");
ListaSeguroOdonto.push("TOPOGRAFO");
ListaSeguroOdonto.push("VIDRACEIRO");
ListaSeguroOdonto.push("VIGIA");
ListaSeguroOdonto.push("AJUDANTE DE ALMOXARIFE");
ListaSeguroOdonto.push("AJUDANTE PRATICO DE BOMBEIRO");
ListaSeguroOdonto.push("AJUDANTE PRATICO DE PEDREIRO");
ListaSeguroOdonto.push("ARMADOR PL");
ListaSeguroOdonto.push("AUX. DE MANUTENÃ???Ã???O MECÃ???NICA");
ListaSeguroOdonto.push("AUXILIAR DE ALOJAMENTO");
ListaSeguroOdonto.push("AUXILIAR DE HIDRAULICA");
ListaSeguroOdonto.push("AUXILIAR DE MANUTENCAO");
ListaSeguroOdonto.push("AUXILIAR DE OBRA");
ListaSeguroOdonto.push("BOMBEIRO PL");
ListaSeguroOdonto.push("BOMBEIRO SUB-OFICIAL");
ListaSeguroOdonto.push("CARPINTEIRO DE FORMA");
ListaSeguroOdonto.push("CARPINTEIRO PL");
ListaSeguroOdonto.push("CASEIRO");
ListaSeguroOdonto.push("COPEIRO");
ListaSeguroOdonto.push("ELETRICISTA OFICIAL");
ListaSeguroOdonto.push("ELETRICISTA SUB-OFICIAL");
ListaSeguroOdonto.push("ESTAGIARIO DE TECNOLOGIA EM CONSTRUCAO ");
ListaSeguroOdonto.push("GREIDISTA");
ListaSeguroOdonto.push("GUARDIAO OBRA");
ListaSeguroOdonto.push("INSTRUTOR DE FORMA I");
ListaSeguroOdonto.push("INSTRUTOR DE FORMA II");
ListaSeguroOdonto.push("JARDINEIRO");
ListaSeguroOdonto.push("LUBRIFICADOR DE VEICULOS AUTOMOTIVOS");
ListaSeguroOdonto.push("MEIO OFICIAL DE DRENAGEM");
ListaSeguroOdonto.push("MEIO OFICIAL DE MONTADOR ESTRUTURAL");
ListaSeguroOdonto.push("MENOR APRENDIZ");
ListaSeguroOdonto.push("MONTADOR DE PRÃ???-MOLDADO");
ListaSeguroOdonto.push("MONTADOR E MANUNTENTOR DE GRUA");
ListaSeguroOdonto.push("MOTORISTA CARRETEIRO");
ListaSeguroOdonto.push("OFICIAL PL");
ListaSeguroOdonto.push("OPERADOR DE  RETRO ESCAVADEIRA");
ListaSeguroOdonto.push("OPERADOR DE DAMPER ");
ListaSeguroOdonto.push("OPERADOR DE EQUIPAMENTO");
ListaSeguroOdonto.push("OPERADOR DE ESCAVADEIRA");
ListaSeguroOdonto.push("OPERADOR DE GUINDAUTO");
ListaSeguroOdonto.push("OPERADOR DE MAQUINA LEVE");
ListaSeguroOdonto.push("OPERADOR DE MAQUINA PESADA");
ListaSeguroOdonto.push("OPERADOR DE MOTONIVELADORA");
ListaSeguroOdonto.push("OPERADOR DE RETROESCAVADEIRA");
ListaSeguroOdonto.push("OPERADOR DE ROLO COMPACTADOR");
ListaSeguroOdonto.push("OPERADOR DE SERRA CIRCULAR");
ListaSeguroOdonto.push("PEDREIRO OFICIAL");
ListaSeguroOdonto.push("PEDREIRO PL");
ListaSeguroOdonto.push("PEDREIRO POLIVALENTE");
ListaSeguroOdonto.push("POCEIRO");
