var Activity = {
	ZERO: 0,
	INICIAR: 4,
	ELABORAR_SM: 5,
	ANALISAR_IMPACTO: 8,
	QUALIFICAR_SM: 11,
	PRE_CGM: 17,
	CGM: 19,
	RESOLVER_PENDENCIAS: 25,
	AGUARDAR: 55,

	GATEWAY_PENDENCIAS: 21,

	FIM_SM_CANCELADA: 15,
	FIM_SM_REPROVADA: 41,
	FIM_SM_CONCLUIDA: 42
};